apiVersion: skaffold/v4beta7
kind: Config
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: arnab17/blog-app-frontend-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arnab17/blog-app-posts-service
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: arnab17/blog-app-comments-service
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: arnab17/blog-app-query-service
      context: query-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: arnab17/blog-app-moderation-service
      context: moderation-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: arnab17/blog-app-eventbus-service
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .